User.create({name: "Rob", username: "@rob", email: "robert.n.kramer@gmail.com", password: "123456"})
User.create({name: "Danny", username: "@danny", email: "dannyevega@gmail.com", password: "123456"})
User.create({name: "Juan", username: "@juan", email: "jpmendez@gmail.com", password: "123456"})
User.create({name: "Julio", username: "@julio", email: "julioindevbootcamp@gmail.com", password: "123456"})
User.create({name: "Stan", username: "@stan", email: "sszetoboom@gmail.com", password: "123456"})
User.create({name: "Nate", username: "@nate", email: "nbeers22@gmail.com", password: "123456"})

UserFollowing.create(user_id: 1, user_following_id: 2)
UserFollowing.create(user_id: 1, user_following_id: 3)
UserFollowing.create(user_id: 1, user_following_id: 4)
UserFollowing.create(user_id: 2, user_following_id: 3)
UserFollowing.create(user_id: 2, user_following_id: 1)
UserFollowing.create(user_id: 2, user_following_id: 4)
UserFollowing.create(user_id: 2, user_following_id: 5)
UserFollowing.create(user_id: 3, user_following_id: 1)
UserFollowing.create(user_id: 3, user_following_id: 5)
UserFollowing.create(user_id: 4, user_following_id: 1)
UserFollowing.create(user_id: 4, user_following_id: 2)
UserFollowing.create(user_id: 4, user_following_id: 3)
UserFollowing.create(user_id: 4, user_following_id: 5)
UserFollowing.create(user_id: 4, user_following_id: 6)
UserFollowing.create(user_id: 5, user_following_id: 3)
UserFollowing.create(user_id: 5, user_following_id: 4)
UserFollowing.create(user_id: 5, user_following_id: 6)
UserFollowing.create(user_id: 6, user_following_id: 1)
UserFollowing.create(user_id: 6, user_following_id: 2)
UserFollowing.create(user_id: 6, user_following_id: 3)

Squeak.create(content: "Today’s date is 10 / 10 / 2014.  It’s so rare that it will never happen again.", user_id: 1)
Squeak.create(content: "My first squeak! Yea!", user_id: 1)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 1)
Squeak.create(content: "My first squeak! Yea!", user_id: 1)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 1)
Squeak.create(content: "My first squeak! Yea!", user_id: 1)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 2)
Squeak.create(content: "My first squeak! Yea!", user_id: 2)
Squeak.create(content: "If Picasso were reincarnated I wonder if he’d return as a flounder, or other fish with both eyes on the same side of its head", user_id: 2)
Squeak.create(content: "My first squeak! Yea!", user_id: 2)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 2)
Squeak.create(content: "My first squeak! Yea!", user_id: 2)
Squeak.create(content: "Bored. Bored. Bored", user_id: 3)
Squeak.create(content: "My first squeak! Yea!", user_id: 3)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 3)
Squeak.create(content: "People in SF are very Strange.", user_id: 3)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 3)
Squeak.create(content: "I need coffee, today!", user_id: 3)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 4)
Squeak.create(content: "My first squeak! Yea!", user_id: 4)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 4)
Squeak.create(content: "I like cheese!", user_id: 4)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 4)
Squeak.create(content: "My first squeak! Yea!", user_id: 4)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 5)
Squeak.create(content: "Beer Rules!", user_id: 5)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 5)
Squeak.create(content: "My first squeak! Yea!", user_id: 5)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 5)
Squeak.create(content: "My first squeak! Yea!", user_id: 5)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 6)
Squeak.create(content: "WTF? Monday already?", user_id: 6)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 6)
Squeak.create(content: "My first squeak! Yea!", user_id: 6)
Squeak.create(content: "Blah blah blah blah blah blah", user_id: 6)
Squeak.create(content: "My first squeak! Yea!", user_id: 6)
